# Generated by Django 3.0.4 on 2020-07-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('city', models.TextField()),
                ('Jobdescription', models.CharField(max_length=100)),
                ('joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
